### ISSUE TITLE
Tip on joining lines

### ISSUE THREAD

**Issue by voyeg3r** [ronakg/dotfiles#2]
On your vimrc you have:

```
" Keep the cursor in place while joining lines
nnoremap J mzJ`z
```
You could do the same without creating any mark, just by doing:
`nnoremap J :join<cr>`

And if you do not want extra any extra space between the joined lines just:
`nnormap gJ :join!<cr>`

In my view avoiding this mapping is better because we have an extra point to leave the cursor in case we want.

I have found another great function to deal with "joining lines"
https://vi.stackexchange.com/a/440/7339
" Like gJ, but always remove spaces
```
fun! JoinSpaceless()
    execute 'normal gJ'
    " Character under cursor is whitespace?
    if matchstr(getline('.'), '\%' . col('.') . 'c.') =~ '\s'
        " When remove it!
        execute 'normal dw'
    endif
endfun
" Map it to a key
nnoremap <Leader>J :call JoinSpaceless()<CR>
```

**Comment by ronakg** [comment]
The mark is to make sure the cursor position doesn't change during the join operation. The `join` command resets the cursor to start of the line.

Am I missing anything else here?
